name: Update Cask

on:
  repository_dispatch:
    types: [update-cask]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update cask
        env:
          VERSION: ${{ github.event.client_payload.version }}
          SHA256: ${{ github.event.client_payload.sha256 }}
        run: |
          printf 'cask "dm-mono-nerd-font" do\n' > Casks/dm-mono-nerd-font.rb
          printf '  version "%s"\n' "$VERSION" >> Casks/dm-mono-nerd-font.rb
          printf '  sha256 "%s"\n\n' "$SHA256" >> Casks/dm-mono-nerd-font.rb
          printf '  url "https://github.com/kilork/dm-mono-nerd-font/releases/download/v%s/dm-mono-nerd-font-%s.tar.gz"\n' "$VERSION" "$VERSION" >> Casks/dm-mono-nerd-font.rb
          printf '  name "DM Mono Nerd Font"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  homepage "https://github.com/kilork/dm-mono-nerd-font"\n\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DM Mono Italic Nerd Font Complete.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DM Mono Light Italic Nerd Font Complete.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DM Mono Light Nerd Font Complete.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DM Mono Medium Italic Nerd Font Complete.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DM Mono Medium Nerd Font Complete.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DM Mono Regular Nerd Font Complete.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DMMonoNerdFont-Italic.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DMMonoNerdFont-Light.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DMMonoNerdFont-LightItalic.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DMMonoNerdFont-Medium.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DMMonoNerdFont-MediumItalic.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf '  font "dm-mono-nerd-font/DMMonoNerdFont-Regular.ttf"\n' >> Casks/dm-mono-nerd-font.rb
          printf 'end\n' >> Casks/dm-mono-nerd-font.rb

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Casks/dm-mono-nerd-font.rb
          git commit -m "Update cask to v${VERSION}" || echo "No changes"
          git push